module.exports = {
  purge: [
    './components/**/*.{vue,js}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    container: {
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
      }
    },
    extend: {
      colors: {
        "tb-blue": "#3099F2",
        "tb-blue-dark": "#1f84da",
        "tb-primary": "#EFF2F5",
        "tb-primary-dark": "#7891A6",
        "tb-black": "#1D1D1D",
        "tb-dark": "#333639",
        "tb-semi-dark": "#D0D9E2",
        "tb-orange": "#FF7000",
        "tb-border": "#E5EAEE",
        "tb-fb": "#4267B2",
        "tb-google": "#F14336",
        "tb-dark-red": "#DC2B2B",
        "tb-green": "#56D11C",
        "tb-true-green": "#48B415",
        "tb-semi-green": "#91C877",
        "tb-yellow": "#EFC036",
        "tb-yellow-dark": "#e0b840",
        "tb-danger": "#EF6236",
        "tb-light-green": "#ADD11C",
        "tb-limegreen": "#ADD11C",
        "tb-red": "#E71D27",
        "tb-black-red": "#c72222",
        "tb-white-green": "#DCF0D2",
        "tb-white-pink": "#F1D9D6",
        "tb-dark-green": "#97C780",
        "tb-blood": "#C38686",
        "tb-white-blood": "#CFACA7",
        "tb-energy-a": "#00A650",
        "tb-energy-b": "#4DBD37",
        "tb-energy-c": "#B2DA17",
        "tb-energy-d": "#FDF100",
        "tb-energy-e": "#FAB10A",
        "tb-energy-f": "#F15C1A",
        "tb-energy-g": "#EB1C24",
      },
    },
  },
  variants: {
    extend: {
      borderWidth: ["responsive", "last", "hover", "focus", "group-hover"],
      padding: ["responsive", "last", "first", "hover"],
      backgroundColor: ["responsive", "hover", "focus", "checked", "group-hover"],
      borderColor: [
        "responsive",
        "hover",
        "focus",
        "checked",
        "last",
        "group-hover",
      ],
      borderRadius: ["responsive", "hover"],
      textColor: ["responsive", "hover", "focus", "last", "group-hover"],
      pointerEvents: ["responsive", "last"],
      zIndex: ["responsive", "hover"],
      cursor: ["responsive", "hover"],
      display: ['responsive', 'group-hover'],
    },
  },
  plugins: [require("@tailwindcss/custom-forms")],
}
